language: node_js
node_js:
  - "0.12"
#  - "iojs"
#  - "0.11"
#  - "0.10"
#  - "0.8"
#  - "iojs-v1.0.4"
before_install:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24 -extension RANDR &&
    export DISPLAY=:99.0 &&
    if [! -d local-build-bin/chrome-linux ] then
      mkdir -p local-build-bin/chrome-linux && curl -Lo /tmp/chrome-linux.zip https://download-chromium.appspot.com/dl/Linux_x64 && unzip /tmp/chrome-linux.zip -d local-build-bin;
     fi
install:
  - npm install -g npm &&
    PATH="$TRAVIS_BUILD_DIR/local-build-bin/chrome-linux:$TRAVIS_BUILD_DIR/local-build-bin:$TRAVIS_BUILD_DIR/node_modules/.bin:$PATH" &&
    npm --version
  - npm install
script:
  - npm test
env:
  global:
    - NPM_CACHE=$HOME/.npm
cache:
  directories:
    - $NPM_CACHE
