language: node_js

node_js:
  - "0.12"
#  - "iojs"
#  - "0.11"
#  - "0.10"
#  - "0.8"
#  - "iojs-v1.0.4"

before_install:
  - sudo apt-get update -qq
  # Upgrade packages
  - sudo apt-get install xvfb chromium-browser firefox -qq
  # Launch xvfb with resolution 1280x1024x24
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24 +extension RANDR &&
    export DISPLAY=:99.0

install:
  - npm install -g npm &&
    PATH="$TRAVIS_BUILD_DIR/local-build-bin/chromium:$TRAVIS_BUILD_DIR/node_modules/.bin:$PATH"
  - npm install

script:
  - node --version && npm --version
  - node test/detect.js --expect chromium firefox phantom | tap-spec
  - alias chromium-browser='chromium-browser --no-sandbox' &&
    npm test

cache:
  directories:
    - $HOME/.npm
    - $TRAVIS_BUILD_DIR/local-build-bin
