language: node_js
node_js:
  - "0.12"
  - "iojs"
  - "0.11"
  - "0.10"
  - "0.8"
  - "iojs-v1.0.4"
before_install:
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24 &&
    export DISPLAY=:99.0
install:
  - npm install -g npm &&
    PATH="$TRAVIS_BUILD_DIR/node_modules/.bin:$PATH" &&
    npm --version
  - npm install
script:
  - npm test
