language: node_js

node_js:
  - "0.12"
  - "iojs"
  - "0.11"
  - "0.10"
  - "0.8"
  - "0.6"
  - "iojs-v1.0.4"

before_install:
  - sudo apt-get update -qq
  # Upgrade used packages
  - sudo apt-get install xvfb firefox phantomjs -qq
  - sudo apt-get autoremove --purge chromium-browser -qq
  # Launch xvfb with resolution 1280x1024x24
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24 +extension RANDR
  - export DISPLAY=:99.0

install:
  # Update npm itself
  - npm install -g npm
  - PATH="`npm bin -g`:`npm bin`:$PATH"
  # Install dependencies
  - npm install

script:
  # Output useful info for debugging
  - node --version
  - npm --version
  # Check browsers' detection got them all
  - node test/detect.js --expect firefox phantom | tap-spec
  # Run tests
  - npm test

# Caching npm parts
cache:
  directories:
    - $HOME/.npm
    - $TRAVIS_BUILD_DIR/node_modules
