language: node_js
node_js:
  - "0.12"
  - "0.11"
  - "0.10"
  - "0.8"
  - "iojs"
  - "iojs-v1.0.4"
install:
  - npm install -g npm &&
    PATH="$TRAVIS_BUILD_DIR/node_modules/.bin:%PATH%" &&
    npm --version
  - npm install
script:
  - npm test
